#sonar.projectKey=atul5021_Auto_services_ba03cb58-d22a-4ab3-bb1f-73bca76709c7

sonar.projectKey=atul5021_Auto_services_ba03cb58-d22a-4ab3-bb1f-73bca76709c7

# Tell SonarQube to scan the entire repository root directory
sonar.sources=.

# Exclude Jenkinsfile or configuration files if needed (optional)
sonar.exclusions=**/*.properties, Jenkinsfile
